services:
  bun-app:
    build: .
    container_name: life_track-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - life_track-net
    volumes:
      - ./:/app

  postgres:
    image: postgres:15-alpine
    container_name: life_track-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: life_track
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - life_track-net

volumes:
  pg-data:


networks:
  life_track-net:
    driver: bridge
